name: Run Tests on PR

on:
  pull_request:

jobs:
  build-and-run:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.0.30319' # Replace with your .NET version
      
    - name: Restore Dependencies
      run: dotnet restore Task2/AutomationFramework/AutomationFramework.csproj

    - name: Build
      run: dotnet build Task2/AutomationFramework/AutomationFramework.csproj

    - name: Test
      run: dotnet test Task2/AutomationFramework/AutomationFramework.csproj
